# Generated by Django 4.1.2 on 2023-01-17 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True)),
                ('bio', models.TextField(default='Biografia do Usuário')),
                ('avatar', models.ImageField(default='avatar/default.jpg', upload_to='avatar/')),
                ('user_profile', models.CharField(choices=[('1', 'Admin'), ('2', 'Student'), ('3', 'Teacher')], default='2', max_length=1)),
                ('ide_theme', models.CharField(choices=[('1', 'Dark'), ('2', 'Light')], default='1', max_length=1)),
                ('language', models.CharField(choices=[('1', 'Português'), ('2', 'Inglês')], default='1', max_length=1)),
                ('email_notification', models.BooleanField(default=True)),
                ('userP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('content', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 19, 0, 29, 461291, tzinfo=datetime.timezone.utc), verbose_name='Created Date')),
                ('userT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('favorite', models.BooleanField(default=False)),
                ('content', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 19, 0, 29, 461291, tzinfo=datetime.timezone.utc), verbose_name='Created Date')),
                ('userR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile')),
            ],
        ),
    ]
