# Generated by Django 4.1.2 on 2023-01-17 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userP',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='repositorio',
            old_name='userR',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='userT',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 19, 2, 14, 760855, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 19, 2, 14, 760855, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
