# Generated by Django 4.1.3 on 2022-12-30 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0002_project_favorite_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('favorite', models.BooleanField(default=False)),
                ('content', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 12, 14, 963538, tzinfo=datetime.timezone.utc), verbose_name='Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.usernew')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 12, 14, 963538, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
