# Generated by Django 4.1.2 on 2023-01-17 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0005_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.CharField(choices=[('1', 'fácil'), ('2', 'médio'), ('3', 'dificil')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 22, 13, 23, 937732, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 22, 13, 23, 937732, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
