# Generated by Django 4.1.2 on 2023-01-18 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0006_tutorial_level_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 46, 28, 729337, tzinfo=datetime.timezone.utc), verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 46, 28, 730337, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 46, 28, 729337, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
