# Generated by Django 4.1.2 on 2023-01-18 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0007_tutorial_edited_at_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 48, 37, 975658, tzinfo=datetime.timezone.utc), verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 48, 37, 976657, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 12, 48, 37, 975658, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
