# Generated by Django 4.1.3 on 2023-01-19 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0009_remove_profile_edited_at_repositorio_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 19, 45, 45, 658895, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 19, 45, 45, 658895, tzinfo=datetime.timezone.utc), verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 19, 45, 45, 657895, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
    ]
