# Generated by Django 4.1.3 on 2023-01-30 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipscode', '0012_alter_repositorio_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('favorite', models.BooleanField(default=False)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 30, 18, 59, 1, 800782, tzinfo=datetime.timezone.utc), verbose_name='Created Date')),
                ('edited_at', models.DateTimeField(default=datetime.datetime(2023, 1, 30, 18, 59, 1, 800782, tzinfo=datetime.timezone.utc), verbose_name='Edited Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipscode.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 18, 59, 1, 799785, tzinfo=datetime.timezone.utc), verbose_name='Created Date'),
        ),
        migrations.DeleteModel(
            name='Repositorio',
        ),
    ]
