version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: mips
      POSTGRES_USER: mips
      POSTGRES_PASSWORD: mips
volumes:
  mips-data:
