name: MipsCode Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: copy files from repository
        uses: actions/checkout@v3
        
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: install dependencies
        run: |
          cd backend
          npm install

      - name: build backend
        run: |
          cd backend
          npm run build

      - name: install dependencies
        run: |
          cd frontend
          npm install

      - name: build frontend
        run: |
          cd frontend
          npm run build
      



      
