name: MipsCode Pipeline

on:
  push:
  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: copy files from repository
        uses: actions/checkout@v3
        
      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: install backend dependencies
        run: |
          cd backend
          npm install

      - name: build backend
        run: |
          cd backend
          npm run build

      - name: install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: build frontend
        run: |
          cd frontend
          npm run build

      - name: prettier check
        run: |
          cd frontend
          npx prettier . --check

      - name: install jscpd
        run: |
          npm install -g jscpd

      - name: detect duplicate code
        run: |
          jscpd --exitCode 1 --pattern "frontend/**/*.js,backend/**/*.js" --config jscpd.json 

      - name: Check circular dependencies in frontend
        run: |
          cd frontend
          npm install madge
          npx madge --circular --extensions ts,tsx src

      - name: Check circular dependencies in backend
        run: |
          cd backend
          npm install madge
          npx madge --circular --e bxtensions js src
